### ISSUE TITLE
Challange - Response hash is incorrect

### ISSUE THREAD

**Issue by mitchvdl** [all-ride/ride-lib-varnish#2]
Depending on the Varnish set-up the secret is able to be without a new line `\n`, however, On [L168 of VarnishAdmin.php](https://github.com/all-ride/ride-lib-varnish/blob/master/src/ride/library/varnish/VarnishAdmin.php#L168) this is enforced. 

https://www.varnish-cache.org/trac/wiki/CLI : Authentication: The gory details
- Challenge string
- Newline (0x0a) character.
- Contents of the secret file
- Challenge string
- Newline (0x0a) character.

**Comment by ride-user** [comment]
Thanks, bugfix released in 1.0.1
